<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\AdminUser;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use \Doctrine\ORM\EntityRepository;

/**
 * AdminUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class AdminUserRepository extends EntityRepository implements UserLoaderInterface
{
    /**
     * @param string $username
     * @return mixed
     */
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.name = :username OR u.email = :email')
            ->setParameter('username', $username)
            ->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();

    }

    /**
     * @param integer $userId
     * @return ArrayCollection
     */
    public function loadUserById($userId)
    {
        return $this->createQueryBuilder('u')
            ->where('u.id = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getOneOrNullResult();

    }

    /**
     * @return ArrayCollection
     */

    public function getUserRoles()
    {
        return $this->createQueryBuilder('u')
            ->select('u.roles')
            ->getQuery()
            ->getResult();


    }
}
