<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 06.09.17
 * Time: 17:07
 */

namespace AdminBundle\Repository;

use AdminBundle\Entity\Permissions;
use AdminBundle\Entity\Roles;
use \Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\Query;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * RolePermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class RolePermissionsRepository extends EntityRepository
{

    /**
     * @param Roles $role
     * @return Permissions[]
     */
    public function loadPermissionsByRole($role)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();



        $result = $qb->select('IDENTITY(rp.perm) as perm')
            ->from('AdminBundle:RolePermissions', 'rp')
            ->where('rp.role = :role')
            ->setParameter('role', $role)
            ->getQuery()
            ->getScalarResult();

//        return $result;

        $mappedResponse = new ArrayCollection();

        array_walk($result, function($item) use ($mappedResponse){
            $mappedResponse->set($item['perm'], $item['perm']);
        });

        return $mappedResponse;

    }
}